### ISSUE TITLE
Rename to "Object Capabilities for Linked Data Systems", ocap-ld for short

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/ocap-ld#3]
Currently we use "ld-ocap" but never mention "Object" in the name "Linked Data Capabilities".  If we do "Object Capabilities for Linked Data Systems" and use "ocap-ld" for short we can remove the ambiguity and make things more consistent with json-ld.

**Comment by talltree** [comment]
Agreed, nice change.

**Comment by cwebber** [comment]
This has been done.
